---
resource_types:
  - name: git-repo
    type: registry-image
    source:
      repository: ghcr.io/jameslikestea/concourse-git-branch
      username: jameslikestea
      password: ((grm_secrets.github_token))
      tag: latest

resources:
  - type: registry-image
    name: image
    icon: docker
    source:
      repository: ghcr.io/jameslikestea/concourse-git-branch
      username: jameslikestea
      password: ((grm_secrets.github_token))
      tag: latest

  - type: git-repo
    name: cgb-repo
    icon: github
    source:
      uri: git@github.com:Jameslikestea/concourse-git-branch.git
      private_key: ((grm_secrets.ssh_key))

jobs:
  - name: build
    public: true
    plan:
      - get: cgb-repo
        version: every
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: cgb-repo
          outputs:
            - name: image
          params:
            CONTEXT: cgb-repo
          run:
            path: build
      - put: image
        params:
          image: image/image.tar
